[build-system]
build-backend = 'mesonpy'
requires = [
  "cython",
  "ninja",
  "meson-python",
  "numpy",
]

[project]
name = "UMPA"
dynamic = ["version"]
requires-python = ">= 3.9"
dependencies = [
  "cython>=3.0.0",
  "numpy",
  "scipy",
  "matplotlib",
  "joblib",
]
authors = [
  {name = "Pierre Thibault", email = "pthibault@units.it"},
  {name = "Fabio De Marco"},
  {name = "Sara Savatovic"},
  {name = "Ronan Smith"},  
]
maintainers = [
  {name = "Darren Thompson", email = "thompsod@ansto.gov.au"},
]
description = "Unified Modulated Pattern Analysis"
readme = "README.md"
license = "GPL-3.0"